[0m15:08:40.367706 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FE79EEDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FEBEBA6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FEC01F810>]}


============================== 15:08:40.390733 | ec52c4de-f4b1-4cd2-96b9-8fbb5bd62e35 ==============================
[0m15:08:40.390733 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:08:40.393740 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Professional\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m15:08:40.395376 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Professional\IT\Study\DBT\airflow\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:08:40.397900 [debug] [MainThread]: Command `dbt deps` failed at 15:08:40.397900 after 0.24 seconds
[0m15:08:40.398836 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FEC012D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FEC013B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022FEC013CD0>]}
[0m15:08:40.399847 [debug] [MainThread]: Flushing usage events
[0m15:08:42.200139 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:50:33.555142 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3F17250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3DBA6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3EBAB50>]}


============================== 16:50:33.561716 | 9bc99896-7465-4d28-b0ff-a8d28f4988e0 ==============================
[0m16:50:33.561716 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:50:33.564224 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Professional\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:50:33.564224 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Professional\IT\Study\DBT\airflow\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:50:33.564224 [debug] [MainThread]: Command `dbt deps` failed at 16:50:33.564224 after 0.09 seconds
[0m16:50:33.564224 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3F1CED0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3F1FFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021FC3F1F650>]}
[0m16:50:33.564224 [debug] [MainThread]: Flushing usage events
[0m16:50:34.476729 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:51:47.892378 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CEEB9790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CECA0E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CEEB9890>]}


============================== 16:51:47.895408 | e30bffdd-7d9d-4c21-b749-c9fd8ed891b5 ==============================
[0m16:51:47.895408 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:51:47.898441 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Professional\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt deps', 'send_anonymous_usage_stats': 'True'}
[0m16:51:47.899761 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Professional\IT\Study\DBT\airflow\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:51:47.899761 [debug] [MainThread]: Command `dbt deps` failed at 16:51:47.899761 after 0.10 seconds
[0m16:51:47.899761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CEF13050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CECA0CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221CEEB95D0>]}
[0m16:51:47.899761 [debug] [MainThread]: Flushing usage events
[0m16:51:48.761141 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:51:59.037443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBF54E7AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBF55178D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBF5517410>]}


============================== 16:51:59.041991 | 8e082140-4b41-4b22-9c78-0e418c4acf0f ==============================
[0m16:51:59.041991 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:51:59.042991 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Professional\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:51:59.079368 [info ] [MainThread]: dbt version: 1.10.4
[0m16:51:59.079368 [info ] [MainThread]: python version: 3.11.9
[0m16:51:59.079368 [info ] [MainThread]: python path: C:\Users\Professional\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
[0m16:51:59.079368 [info ] [MainThread]: os info: Windows-10-10.0.22000-SP0
[0m16:51:59.163498 [info ] [MainThread]: Using profiles dir at C:\Users\Professional\.dbt
[0m16:51:59.164498 [info ] [MainThread]: Using profiles.yml file at C:\Users\Professional\.dbt\profiles.yml
[0m16:51:59.164498 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Professional\IT\Study\DBT\airflow\dbt_project.yml
[0m16:51:59.166499 [info ] [MainThread]: adapter type: postgres
[0m16:51:59.166499 [info ] [MainThread]: adapter version: 1.9.0
[0m16:51:59.167498 [info ] [MainThread]: Configuration:
[0m16:51:59.168499 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:51:59.169578 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:51:59.171098 [info ] [MainThread]: Required dependencies:
[0m16:51:59.172093 [debug] [MainThread]: Executing "git --help"
[0m16:51:59.221336 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:51:59.221336 [debug] [MainThread]: STDERR: "b''"
[0m16:51:59.221336 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:51:59.221336 [info ] [MainThread]: Connection:
[0m16:51:59.227389 [info ] [MainThread]:   host: localhost
[0m16:51:59.227389 [info ] [MainThread]:   port: 4001
[0m16:51:59.227389 [info ] [MainThread]:   user: postgres
[0m16:51:59.227389 [info ] [MainThread]:   database: dwh_flights
[0m16:51:59.227389 [info ] [MainThread]:   schema: intermediate
[0m16:51:59.227389 [info ] [MainThread]:   connect_timeout: 10
[0m16:51:59.227389 [info ] [MainThread]:   role: None
[0m16:51:59.231928 [info ] [MainThread]:   search_path: None
[0m16:51:59.232704 [info ] [MainThread]:   keepalives_idle: 0
[0m16:51:59.233702 [info ] [MainThread]:   sslmode: None
[0m16:51:59.233702 [info ] [MainThread]:   sslcert: None
[0m16:51:59.234701 [info ] [MainThread]:   sslkey: None
[0m16:51:59.235701 [info ] [MainThread]:   sslrootcert: None
[0m16:51:59.235701 [info ] [MainThread]:   application_name: dbt
[0m16:51:59.238337 [info ] [MainThread]:   retries: 1
[0m16:51:59.239868 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m16:51:59.528480 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m16:51:59.601821 [debug] [MainThread]: Using postgres connection "debug"
[0m16:51:59.601821 [debug] [MainThread]: On debug: select 1 as id
[0m16:51:59.601821 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:51:59.718201 [debug] [MainThread]: SQL status: SELECT 1 in 0.121 seconds
[0m16:51:59.718201 [debug] [MainThread]: On debug: Close
[0m16:51:59.718201 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m16:51:59.718201 [info ] [MainThread]: [31m1 check failed:[0m
[0m16:51:59.728249 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Professional\IT\Study\DBT\airflow\dbt_project.yml> not found

[0m16:51:59.729200 [debug] [MainThread]: Command `dbt debug` failed at 16:51:59.729200 after 0.78 seconds
[0m16:51:59.729200 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:51:59.729200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBF54B9590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBF5517210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FBEF89D5D0>]}
[0m16:51:59.729200 [debug] [MainThread]: Flushing usage events
[0m16:52:00.579287 [debug] [MainThread]: An error was encountered while trying to flush usage events
